version: '3.4'

services:
  redis_flowerSpotCache:
    ports:
      - 6379:6379

  postgres_flowerspotdb:
    container_name: flowerSpotDb
    restart: unless-stopped
    environment:
       - POSTGRES_USER=flowerSpot
       - POSTGRES_PASSWORD=flowerSpot123
       - PGDATA=/var/lib/postgresql/data/pgdata
       - POSTGRES_DB=FlowerSpot
    ports:
       - 5432:5432
    volumes:
       - database-data:/var/lib/postgresql/data/ 
  
  pgadmin:
    environment:
       - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
       - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
       - "5050:80"
    restart: unless-stopped
    volumes:
       - database-data:/var/lib/postgresql/data/ 

  flowerspot.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      #- ASPNETCORE_URLS=https://+:443;http://+:80
    depends_on:
      - postgres_flowerspotdb
    ports:
      - "15000:80"
      - "15001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

volumes:
  database-data:
  pgadmin: