//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerSpot.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowerSpot.Domain.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not publish Flowers..
        /// </summary>
        public static string FailedUpdatingFlowers {
            get {
                return ResourceManager.GetString("FailedUpdatingFlowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not publish Sighting Likes..
        /// </summary>
        public static string FailedUpdatingSightingLikes {
            get {
                return ResourceManager.GetString("FailedUpdatingSightingLikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not publish Sightings..
        /// </summary>
        public static string FailedUpdatingSightings {
            get {
                return ResourceManager.GetString("FailedUpdatingSightings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find Flower with Flower Id {0}..
        /// </summary>
        public static string FlowerNotFound {
            get {
                return ResourceManager.GetString("FlowerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required and must be in range -{1} to {1}..
        /// </summary>
        public static string InvalidCoordinate {
            get {
                return ResourceManager.GetString("InvalidCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flower name must not be empty and contain maximum 50 characters..
        /// </summary>
        public static string InvalidFlowerName {
            get {
                return ResourceManager.GetString("InvalidFlowerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request must contain the name of stored image..
        /// </summary>
        public static string InvalidImageRef {
            get {
                return ResourceManager.GetString("InvalidImageRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} does not have permission to delete this sighting..
        /// </summary>
        public static string MissingPermission {
            get {
                return ResourceManager.GetString("MissingPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain 8 to 20 characters, at least one letter, one number, and one special character..
        /// </summary>
        public static string PasswordMustContain {
            get {
                return ResourceManager.GetString("PasswordMustContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain minimum 8 and maximum of 20 characters..
        /// </summary>
        public static string PasswordMustContainLogin {
            get {
                return ResourceManager.GetString("PasswordMustContainLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string RequiredProperty {
            get {
                return ResourceManager.GetString("RequiredProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find Sighting with Sighting Id {0}..
        /// </summary>
        public static string SightingNotFound {
            get {
                return ResourceManager.GetString("SightingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in again..
        /// </summary>
        public static string UsernameClaimNotFound {
            get {
                return ResourceManager.GetString("UsernameClaimNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must contain minimum 3 and maximum of 20 characters..
        /// </summary>
        public static string UsernameMustContain {
            get {
                return ResourceManager.GetString("UsernameMustContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with username {0} already exists..
        /// </summary>
        public static string UsernameTaken {
            get {
                return ResourceManager.GetString("UsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find User with Username {0}..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password entered..
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
